#!/bin/bash

mvn sonar:sonar -Dsonar.host.url=http://sonarcloud.io \
              -Dsonar.projectKey=eric-legoff-sonarsource_squid-2095 \
              -Dsonar.login=48efab345dfb61df0a85db95439a74ba20613324 \
              -Dsonar.organization=eric-legoff-sonarsource-github \
              -Donar.projectName=squid_2095 
